version: "3"

services:
  rabbitmq:
    container_name: restaurant-rabbitmq
    image: rabbitmq:3.8
    networks:
      - restaurant-app

  mysql:
    container_name: restaurant-mysql
    image: mysql:latest
    restart: always
    env_file: ./apps/order-service/.env
    networks:
      - restaurant-app

  order-service:
    build:
      context: ./apps/order-service
    container_name: restaurant-order-service
    restart: always
    ports:
      - 3939:3939
    depends_on:
      - rabbitmq
      - mysql
    command:
      - /bin/sh
      - -c
      - |
        npx prisma migrate deploy
        npm run start:prod
    networks:
      - restaurant-app

  notif-service:
    build:
      context: ./apps/notif-service
    restart: always
    container_name: restaurant-notif-service
    depends_on:
      - order-service
    command: ["npm", "run", "start:prod"]
    networks:
      - restaurant-app

  kitchen-service:
    build:
      context: ./apps/kitchen-service
    restart: always
    container_name: restaurant-kitchen-service
    depends_on:
      - order-service
    command:
      - /bin/sh
      - -c
      - |
        npx prisma generate
        npm run start:prod
    networks:
      - restaurant-app

networks:
  restaurant-app:
