version: "3"

services:
  mysql:
    container_name: restaurant-mysql
    image: mysql:latest
    restart: always
    env_file: ./apps/order-service/.env
    ports:
      - "3306:3306"
    networks:
      - restaurant-app

  rabbitmq:
    container_name: restaurant-rabbitmq
    image: rabbitmq:3.8
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - restaurant-app

networks:
  restaurant-app:
